# NUMPY

In [ ]:
'''
GOOD RESOURCES FOR NUMPY:

https://www.python-course.eu/numpy.php
https://numpy.org/devdocs/user/absolute_beginners.html#what-is-an-array
scipy-lectures.org/intro/numpy/array_object.html#numpy-arrays
https://numpy.org/doc/stable/user/quickstart.html
'''



While NumPy by itself does not provide modeling or scientific functionality, having
an understanding of NumPy arrays and array-oriented computing will help you use
tools with array-oriented semantics, like pandas, much more effectively.

For most data analysis applications, the main areas of functionality I’ll focus on are:
*  Fast vectorized array operations for data munging and cleaning, subsetting and
filtering, transformation, and any other kinds of computations
*  Common array algorithms like sorting, unique, and set operations
*  Efficient descriptive statistics and aggregating/summarizing data
*  Data alignment and relational data manipulations for merging and joining
together heterogeneous datasets
*  Expressing conditional logic as array expressions instead of loops with if-elif-
else branches
*  Group-wise data manipulations (aggregation, transformation, function applica‐
tion)
    
One of the reasons NumPy is so important for numerical computations in Python is
because it is designed for efficiency on large arrays of data. There are a number of
reasons for this:
*  NumPy internally stores data in a contiguous block of memory, independent of
other built-in Python objects. NumPy’s library of algorithms written in the C lan‐
guage can operate on this memory without any type checking or other overhead.
NumPy arrays also use much less memory than built-in Python sequences.
*  NumPy operations perform complex computations on entire arrays without the
need for Python for loops.



In [ ]:
# To give you an idea of the performance difference, consider a NumPy array of one
# million integers, and the equivalent Python list:

import numpy as np
import matplotlib as plt
my_arr = np.arange(1000000)
my_list = list(range(1000000))

# Now let’s multiply each sequence by 2:
%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 15.1 ms, sys: 15.6 ms, total: 30.7 ms
Wall time: 31.8 ms
CPU times: user 584 ms, sys: 141 ms, total: 724 ms
Wall time: 725 ms


## THE BASICS

### **The NumPy ndarray: A Multidimensional Array Object**

In [ ]:
'''
the basic aray object of numpy is called ndarray or n dimnesional array synonymous to dataframe in pandas
'''

In [ ]:
# 1D array

In [ ]:
data = np.array([1,2,0,4,5,6])

In [ ]:
data

array([1, 2, 0, 4, 5, 6])

In [ ]:
type(data)

numpy.ndarray

In [ ]:
# 2D array

In [ ]:
a = np.array([[1,2,3,4,5,6],['a','b','c','d','e','f']])

In [ ]:
a

array([['1', '2', '3', '4', '5', '6'],
       ['a', 'b', 'c', 'd', 'e', 'f']], dtype='<U21')

In [ ]:
a.dtype

dtype('<U21')

In [ ]:
data = np.random.randn(2, 3)

In [ ]:
data

array([[ 1.53362505, -0.7803735 ,  0.18073012],
       [ 1.09316898, -0.41022123, -1.82196185]])

In [ ]:
data * 10

array([[ 15.33625045,  -7.80373504,   1.80730123],
       [ 10.93168982,  -4.10221233, -18.21961854]])

### **SOME USEFUL ATTRIBUTES OF NUMPY ARRAY**

In [ ]:
'''
An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type. Every array has a shape , a tuple indicating the
size of each dimension, and a dtype , an object describing the data type of the array
'''

In [ ]:
# shape of the data
data.shape

(2, 3)

In [ ]:
# datatype of the data
data.dtype

dtype('float64')

In [ ]:
# dimensions of the array
data.ndim

2

In [ ]:
# no. of elements in the array 
data.size

6

In [ ]:
# Length of one array element in bytes.
data.itemsize

8

In [ ]:
# totalsize
data.nbytes

48

### **CREATING ARRAYS WITH DIFFERENT METHODS**

**1. array of 0s**

In [ ]:


# 1d
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 2d
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**2. array of 1s**

In [ ]:


# 1d
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((10,2),dtype = "int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

**3. empty arrays**

In [ ]:



# The function empty creates an array whose initial content is random and depends on the state of the memory.
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element 
# afterwards!

# 1D
np.empty(2)

array([5.73021895e-300, 6.91515971e-310])

In [ ]:
# 2D
np.empty((2, 3))


array([[4.63745813e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

**4. creating identity matrix**

In [ ]:


np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**5. creating an array with a range of elements using arange method:**

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

**6. You can also use np.linspace() to create an array with values that are spaced linearly in a specified '
interval:**

In [ ]:
np.linspace(2,10, num=9,dtype = np.int32)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [ ]:
'''
Function                                Description
-------------------------------------------------------------------------------------------------------------
array                                   Convert input data (list, tuple, array, or other sequence type) to an
                                        ndarray either by inferring a dtype or explicitly specifying a dtype; 
                                        copies the input data by default
        
asarray                                 Convert input to ndarray, but do not copy if the input is already an
                                        ndarray
    
arange                                  Like the built-in range but returns an ndarray instead of a list

ones,ones_like                          Produce an array of all 1s with the given shape and dtype; ones_like 
                                        takes another array and produces a ones array of the same shape and dtype

zeros,zeros_like                        Like ones and ones_like but producing arrays of 0s instead

empty,empty_like                        Create new arrays by allocating new memory, but do not populate with
                                        any values like ones and zeros

full                                    Produce an array of the given shape and dtype with all values set to 
                                        the indicated “fill value”

full_like                               full_like takes another array and produces a filled array of the same 
                                        shape and dtype
    
eye, identity                           Create a square N × N identity matrix (1s on the diagonal and 0s
                                                                               elsewhere)

'''

### **DATATYPES OF NDARRAY**

In [ ]:
'''
numpy has its own datatypes derived from original datatypes of python. However you can use basic python data 
types too.
you can learn more about numpy datatypes here: https://numpy.org/devdocs/user/basics.types.html
'''

In [ ]:
# Specifying your data type

# While the default data type is floating point (np.float64), you can explicitly specify which data type you 
# want using the dtype keyword.
x = np.ones(2, dtype=np.int64)

In [ ]:
x

array([1, 1])

astype() method:

In [ ]:
# You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(np.float64)
print(arr.dtype)

int64
float64
[1. 2. 3. 4. 5.]


## PLAYING WITH DIMENSIONS OF AN ARRAY

### **FLATTENING MULTIDIMENSIONAL ARRAY**


There are two methods to flatten a multidimensional array:
1. flatten()
2. ravel()

**1. flatten()**

In [ ]:
'''
flatten is a ndarry method with an optional keyword parameter "order". order can have the values "C", "F" and
"A". The default of order is "C". 
"C" means to flatten C style in row-major ordering, i.e. the rightmost index "changes the fastest" or in 
other words: In row-major order, the row index varies the slowest, and 
the column index the quickest, so that a[0,1] follows [0,0].

"F" stands for Fortran column-major ordering. 

"A" means preserve the the C/Fortran ordering.
'''


A = np.array([
                  [
                   [ 0,  1],
                   [ 2,  3],
                   [ 4,  5],
                   [ 6,  7]
                  ],
              
                  [
                   [ 8,  9],
                   [10, 11],
                   [12, 13],
                   [14, 15]
                  ],
               
                  [
                   [16, 17],
                   [18, 19],
                   [20, 21],
                   [22, 23]
                  ]
             ])
print(A.shape)
print()
Flattened_X = A.flatten()
print(Flattened_X)
print()
print(A.flatten(order="C"))
print()
print(A.flatten(order="F"))
print()
print(A.flatten(order="A"))



(3, 4, 2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


**2. ravel()**

In [ ]:
'''
The order of the elements in the array returned by ravel() is normally "C-style".

ravel(a, order='C')

ravel returns a flattened one-dimensional array. A copy is made only if needed.

The optional keyword parameter "order" can be 'C','F', 'A', or 'K'

'C': C-like order, with the last axis index changing fastest, back to the first axis index changing slowest. "C" is the default!

'F': Fortran-like index order with the first index changing fastest, and the last index changing slowest.

'A': Fortran-like index order if the array "a" is Fortran contiguous in memory, C-like order otherwise.

'K': read the elements in the order they occur in memory, except for reversing the data when strides are negative.

'''

print(A.ravel())

print(A.ravel(order="C"))

print(A.ravel(order="F"))

print(A.ravel(order="A"))

print(A.ravel(order="K"))



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### **CHANGING THE DIMENSIONS OF THE ARRAY**

1. reshape() method
2. resize() method

**1. reshape() method**

In [ ]:
a = np.ones((2,3),dtype = np.int32)
a


array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
a.reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
c = np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# if one of the arguments to the reshape function is -1, it automatically calculates that argument based on
# other arguments

c.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**2. resize() method**


In [ ]:
# reshape returns the a new array with the modified shape whereas resize modifies the array itself

In [ ]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c.resize(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# we cannot use -1 with resize

### **ADDING MORE DIMENSIONS TO EXISTING ARRAYS**

In [ ]:
'''

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 
1D array will become a 2D array, a 2D array will become a 3D array, and so on.

'''


In [ ]:
# for example lets start with the array:

a = np.array([1, 2, 3, 4, 5, 6])
a.shape


(6,)

In [ ]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis,0:6]
a2.shape

(1, 6)

In [ ]:
# You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. 
# For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
# You can also expand an array by inserting a new axis at a specified position with np.expand_dims.
# For example, if you start with this array:
a = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
# You can use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
# You can add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## INDEXING, SLICING, SELECTIONS AND ITERATING OF ARRAYS

### **INDEXING AND SLICING**

In [ ]:
# The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):


1d arrays:

In [ ]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[3]

27

In [ ]:
a[:4]

array([ 0,  1,  8, 27])

In [ ]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [ ]:
a[::2]

array([  0,   8,  64, 216, 512])

nd arrays:

In [ ]:
 def f(x,y):
     return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [ ]:
b[2,3]

23

In [ ]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [ ]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [ ]:
b[1:3, : ]                      # each column in the second and third row of b


array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [ ]:
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:


b[-1]                                  # the last row. Equivalent to b[-1,:]


# The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to 
# represent the remaining axes. 

array([40, 41, 42, 43])

In [ ]:
'''
NumPy also allows you to write this using dots as b[i,...].
The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an
array with 5 axes, then

    x[1,2,...] is equivalent to x[1,2,:,:,:],

    x[...,3] to x[:,:,:,:,3] and

    x[4,...,5,:] to x[4,:,:,5,:].

'''

c = np.array( [
                [
                 [  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]
                ],
                f[
                 [100,101,102],
                 [110,112,113]
                ]
             ])


In [ ]:
c.shape

(2, 2, 3)

In [ ]:
print(c[1,...])                          # same as c[1,:,:] or c[1]

[[100 101 102]
 [110 112 113]]


In [ ]:
print(c[...,2])                                # same as c[:,:,2]

[[  2  13]
 [102 113]]


### **ITERATING OVER AN ARRAY**

In [ ]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [ ]:
for ele in c.flat:
    print(ele)

0
1
2
10
12
13
100
101
102
110
112
113


### **SELECTING FROM AN ARRAY**

In [ ]:
 a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# You can easily print all of the values in the array that are less than 5.
print(a[a < 5])

[1 2 3 4]


In [ ]:
# You can also select, for example, numbers that are equal to or greater than 5, and use that condition to 
# index an array.

five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
# You can select elements that are divisible by 2:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
# Or you can select elements that satisfy two conditions using the & and | operators:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
# You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# You can use np.nonzero() to print the indices of elements that are, for example, less than 7:
b = np.nonzero(a < 7)
print(b)

#In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row 
# indices where these values are found, and the second array represents the column indices where the values are
# found.

(array([0, 0, 0, 0, 1, 1]), array([0, 1, 2, 3, 0, 1]))


In [ ]:
# If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over 
# the list of coordinates, and print them. For example:

list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
     print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)


## MULTIDIMENSIONAL INDEX ITERATORS

numpy.flat and numpy.ndenumerate

In [ ]:
for x in A.flat:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
 a = np.array([[1, 2], [3, 4]])

for index, x in np.ndenumerate(a):

    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


## STACKING OVER DIFFERENT ARRAYS 

**hstack() and hstack()**

You can stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:
However these functions dont add a new dimension on their own

In [ ]:
a1 = np.array([[1, 1],[2, 2]])

a2 = np.array([[3, 3],[4, 4]])

In [ ]:
# You can stack them vertically with vstack:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
# Or stack them horizontally with hstack:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

**column_stack() and row_stack()**

In [ ]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 
# 2D arrays:
rg = np.random.default_rng(1)  # creates instance of a random no. generator from numpy

from numpy import newaxis

a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))

np.column_stack((a,b))     # with 2D arrays

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [ ]:
 np.hstack((a,b))           # the result is same as the arrays are 2d arrays

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [ ]:
a = np.array([4.,2.])
b = np.array([3.,8.])


In [ ]:
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [ ]:
np.hstack((a,b))          # returns a 1d array

array([4., 2., 3., 8.])

In [ ]:
a[:,newaxis]   # viewing it as a 2d array by adding a new axis

array([[4.],
       [2.]])

In [ ]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [ ]:
np.hstack((a[:,newaxis],b[:,newaxis]))  # now the result is same as we used 2d arrays

array([[4., 3.],
       [2., 8.]])

In [ ]:
# On the other hand,the function row_stack is equivalent to vstack for any input arrays. In fact, 
# row_stack is an alias for vstack:

np.column_stack is np.hstack

False

In [ ]:
np.row_stack is np.vstack

True

## CONCATENATING 2 ARRAYS using concatenate()

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
# stacked as a row
print(np.concatenate((a, b), axis=0))

# stacked as column
print()
print(np.concatenate((a, b.T), axis=1))

# if axis = None, the arrays are first flattened and then concatenated
print()
print(np.concatenate((a, b), axis=None))


[[1 2]
 [3 4]
 [5 6]]

[[1 2 5]
 [3 4 6]]

[1 2 3 4 5 6]


In [ ]:
'''
In general, for arrays with more than two dimensions, hstack stacks along their second axes, vstack stacks 
along their first axes, and concatenate allows for an optional arguments giving the number of the axis along 
which the concatenation should happen.
'''

## SPLITTING ARRAYS INTO SMALLER ARRAYS

**hsplit() method**  - always splits column wise irrespective of the dimension

In [ ]:
# Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally 
# shaped arrays to return, or by specifying the columns after which the division should occur:

In [ ]:
a = np.floor(10*rg.random((2,12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [ ]:
# split in 3 equal parts column wise
np.hsplit(a,3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [ ]:
# Split a after the third and the fourth column
np.hsplit(a,(3,4))

[array([[6., 7., 6.],
        [8., 5., 5.]]),
 array([[9.],
        [7.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2.],
        [1., 8., 6., 7., 1., 8., 1., 0.]])]

**vsplit() method** -  - always splits row wise irrespective of the dimension

In [ ]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [ ]:
np.vsplit(x,(3, 6))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

## COPIES AND VIEWS

**1.No Copy at All**

In [ ]:

# Simple assignments make no copy of objects or their data.

a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object
True


True

**2.View or Shallow Copy**

In [ ]:

# Different array objects can share the same data. The view method creates a new array object that looks at the
# same data.
c = a.view()
c is a


False

In [ ]:
c.base is a                        # c is a view of the data owned by a

True

In [ ]:
c.flags.owndata

False

In [ ]:
c = c.reshape((2, 6))                      # a's shape doesn't change
a.shape

(3, 4)

In [ ]:
c[0, 4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [ ]:
# slicing an array returns a view of it

**3.Deep Copy**

In [ ]:
# The copy method makes a complete copy of the array and its data.

d = a.copy()                          # a new array object with new data is created
d is a

False

In [ ]:
d.base is a                           # d doesn't share anything with a

False

In [ ]:
d[0,0] = 9999
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

## BASIC OPERATIONS

**Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.**

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [ ]:
c = a-b
c

array([20, 29, 38, 47])

In [ ]:
b**2


array([0, 1, 4, 9])

In [ ]:
10*np.sin(a)


array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
a<35

array([ True,  True, False, False])

**Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:**

In [ ]:
A = np.array( [[1,1],
           [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A * B                       # elementwise product



array([[2, 0],
       [0, 4]])

In [ ]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

**Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.**

In [ ]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
b += a
b



array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [ ]:
a += b                            # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

**When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).**

In [ ]:
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(b)
b.dtype.name

[0.         1.57079633 3.14159265]


'float64'

In [ ]:
c = a+b
print(c)
c.dtype.name

[1.         2.57079633 4.14159265]


'float64'

In [ ]:
d = np.exp(c*1j)
print(d)
d.dtype.name
'complex128'

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

**Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.**

In [ ]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [ ]:
a.sum()

3.1057109529998157

In [ ]:
a.min()

0.027559113243068367

In [ ]:
a.max()

0.8277025938204418

**By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:**

In [ ]:
>>> b = np.arange(12).reshape(3,4)
>>> b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
>>> b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [ ]:
>>> b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [ ]:
>>> b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [ ]:
'''
Sorting an array
what is broadcasting and broadcasting rules
generating random numbers using np.random


'''